# K8sToolbox DaemonSet Manifest with ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8stoolbox-cluster-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8stoolbox-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: k8stoolbox-cluster-admin
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8stoolbox-cluster-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8stoolbox-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: k8stoolbox-cluster-admin
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8stoolbox-daemonset
  namespace: kube-system
  labels:
    app: k8stoolbox
spec:
  selector:
    matchLabels:
      app: k8stoolbox
  template:
    metadata:
      labels:
        app: k8stoolbox
    spec:
      serviceAccountName: k8stoolbox-cluster-admin
      containers:
        - name: k8stoolbox
          image: narmidm/k8stoolbox:latest
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
