{{- if not .Values.deployment.useDaemonSet }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "k8stoolbox.fullname" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "k8stoolbox.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.security.createServiceAccount }}
  serviceAccountName: {{ include "k8stoolbox.serviceAccountName" . }}
  {{- end }}
  {{- with .Values.security.podSecurityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command: ["tail", "-f", "/dev/null"]
      {{- with .Values.security.containerSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.config.enableWebUI }}
      ports:
        - name: http
          containerPort: {{ .Values.config.webUIPort }}
          protocol: TCP
        {{- if .Values.monitoring.enablePrometheus }}
        - name: metrics
          containerPort: {{ .Values.monitoring.metricsPort }}
          protocol: TCP
        {{- end }}
      {{- end }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      {{- if or .Values.volumes.createTmpVolume .Values.volumes.mountHostRoot (gt (len .Values.volumes.additional) 0) }}
      volumeMounts:
        {{- if .Values.volumes.createTmpVolume }}
        - name: tmp-volume
          mountPath: /tmp
        {{- end }}
        {{- if .Values.volumes.mountHostRoot }}
        - name: host-root
          mountPath: /host
        {{- end }}
        {{- range .Values.volumes.additional }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if gt (len .Values.config.env) 0 }}
      env:
        {{- toYaml .Values.config.env | nindent 8 }}
      {{- end }}
  {{- if or .Values.volumes.createTmpVolume .Values.volumes.mountHostRoot (gt (len .Values.volumes.additional) 0) }}
  volumes:
    {{- if .Values.volumes.createTmpVolume }}
    - name: tmp-volume
      emptyDir: {}
    {{- end }}
    {{- if .Values.volumes.mountHostRoot }}
    - name: host-root
      hostPath:
        path: /
        type: Directory
    {{- end }}
    {{- range .Values.volumes.additional }}
    - name: {{ .name }}
      {{- omit . "name" "mountPath" "subPath" | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.deployment.useDaemonSet }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8stoolbox.fullname" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "k8stoolbox.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "k8stoolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8stoolbox.labels" . | nindent 8 }}
        {{- with .Values.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.security.createServiceAccount }}
      serviceAccountName: {{ include "k8stoolbox.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          {{- with .Values.security.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.config.enableWebUI }}
          ports:
            - name: http
              containerPort: {{ .Values.config.webUIPort }}
              protocol: TCP
            {{- if .Values.monitoring.enablePrometheus }}
            - name: metrics
              containerPort: {{ .Values.monitoring.metricsPort }}
              protocol: TCP
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.volumes.createTmpVolume .Values.volumes.mountHostRoot (gt (len .Values.volumes.additional) 0) }}
          volumeMounts:
            {{- if .Values.volumes.createTmpVolume }}
            - name: tmp-volume
              mountPath: /tmp
            {{- end }}
            {{- if .Values.volumes.mountHostRoot }}
            - name: host-root
              mountPath: /host
            {{- end }}
            {{- range .Values.volumes.additional }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if gt (len .Values.config.env) 0 }}
          env:
            {{- toYaml .Values.config.env | nindent 12 }}
          {{- end }}
      {{- if or .Values.volumes.createTmpVolume .Values.volumes.mountHostRoot (gt (len .Values.volumes.additional) 0) }}
      volumes:
        {{- if .Values.volumes.createTmpVolume }}
        - name: tmp-volume
          emptyDir: {}
        {{- end }}
        {{- if .Values.volumes.mountHostRoot }}
        - name: host-root
          hostPath:
            path: /
            type: Directory
        {{- end }}
        {{- range .Values.volumes.additional }}
        - name: {{ .name }}
          {{- omit . "name" "mountPath" "subPath" | toYaml | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end }} 