name: CD Pipeline

on:
  release:
    types: [created]

jobs:
  push:
    name: Push Multi-Arch Docker Image to Registry
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Extract version from release tag
      - name: Extract Version from Release Tag
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 5: Build and Push Multi-Architecture Docker Image
      - name: Build and Push Multi-Arch Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t narmidm/k8stoolbox:latest -t narmidm/k8stoolbox:${{ env.VERSION }} -f docker/Dockerfile --push .
